web/components/src/List/List.tsx
Reverts equinor/energyvision#1703
=> Revert "💄 remove vertical spacing for list #1632"

web/pageComponents/shared/iframe/IFrame.tsx
Reverts equinor/energyvision#1681
=> Revert "⚡️Lazy load iframe embeds #1593"

web/pageComponents/shared/ImageCarousel/ImageCarousel.tsx, web/pageComponents/shared/ImageCarousel/ImageCarouselItem.tsx
=> 🐛 Display pagination number in carousel #1670

.github/workflows/DEV-studio-v3.yml, .github/workflows/DEV-studio.yml, .github/workflows/DEV-web.yaml, .github/workflows/deploy-studios/action.yaml, .github/workflows/deploy-v3/action.yaml, .github/workflows/deploy-websites/action.yaml
=> ⚗️ Fix CI/CD for dev #1735

.github/workflows/DEV-studio-v3.yml, .github/workflows/DEV-studio.yml, .github/workflows/DEV-web.yaml, .github/workflows/deploy-studios/action.yaml, .github/workflows/deploy-v3/action.yaml, .github/workflows/deploy-websites/action.yaml
Reverts equinor/energyvision#1736
=> Revert "⚗️ Fix CI/CD for dev #1735"

web/pages/robots.txt.ts, web/pages/sitemap.xml.ts
=> ✨ 404 for non prod domains (robots, sitemap) #1717

.github/workflows/PREPROD-studios-v3.yaml
=> 👷 Deploy studio v3 to preprod #1745

.github/workflows/PREPROD-studios-v3.yaml, .github/workflows/PREPROD-studios.yaml
=> 👷 Deploy studios v2 (wait with v3 release) #1745

web/pageComponents/shared/iframe/RequestConsentContainer.tsx, web/pages/_app.tsx, web/pages/_document.tsx, web/styles/components/cookieBot.ts
=> 🐛 Fix cookiebot dialog languages on lang switch #1701

sanityv3/schemas/documents/header/sharedHeaderFields.ts, studio/schemas/documents/header/sharedHeaderFields.ts, web/components/src/HLSPlayer/index.tsx, web/pageComponents/shared/Hero/LoopingVideo.tsx, web/pageComponents/shared/VideoPlayer.tsx, web/pageComponents/shared/VideoPlayerCarousel.tsx, web/types/types.ts
Had to make some adjustment to the play/pause logic due to the usecase of looping videos that will autoplay when entering a site.
=> ✨ Play button on all videos #1638

sanityv3/helpers/referenceFilters.ts, sanityv3/schemas/documents/subMenu.tsx, studio/helpers/referenceFilters.ts, studio/schemas/documents/subMenu.tsx
=> ✨ Add magazines to menu featured content #1689

.github/workflows/DEV-studio-v3.yml
=> ⏪️ Revert changes #1780

.github/workflows/PROD-webs.yaml
=> 💚 Checkout before trying to get token #78

web/pages/sitemap.xml.ts
=> 🐛 Fix sitemap displaying 404 in prod #1792

sanityv3/src/lib/structure/items/AssetLibrary.js
=> 🐛 Display hidden menu #1858

web/public/.well-known/security.txt
=> 🔒️ Fix security.txt file #1884

web/pageComponents/pageTemplates/News.tsx, web/pageComponents/shared/portableText/components/news/Fact.tsx, web/pageComponents/shared/portableText/components/news/FigureWithLayout.tsx, web/pageComponents/shared/portableText/components/news/Quote.tsx
=> 💄 Improve spacing for factboxes #1753

web/pageComponents/shared/VideoPlayer.tsx
=> 🐛 Show correct aspect ratio when in full screen #1865

sanityv3/plugins/asset-source-fotoware/src/FotowareAssetSource.tsx, sanityv3/plugins/asset-source-fotoware/src/types.ts
=> ✨ Improve fotoware integration #1859

web/pages/magasin/index.global.tsx, web/pages/magazine/index.global.tsx, web/pages/news/index.global.tsx, web/pages/nyheter/index.global.tsx
=> ⚗️ Explicity set cache policy for SSR pages #1944

web/pageComponents/shared/MagazineTagBar.tsx, web/pages/magasin/index.global.tsx, web/pages/magazine/index.global.tsx, web/pages/news/index.global.tsx, web/pages/nyheter/index.global.tsx
=> 🔥 Cleanup not needed code and fix console warning #1944

search/IndexSanityContent/events/index.ts, search/IndexSanityContent/localNews/index.ts, search/IndexSanityContent/magazine/index.ts, search/IndexSanityContent/news/index.ts, search/IndexSanityContent/topic/index.ts, web/pages/magazine/index.global.tsx
=> 🐛 Prevent race condition between delete and update requests #1998

web/package.json, web/pages/api/rss/groq.global.ts, web/pages/api/rss/index.global.ts, web/pnpm-lock.yaml
=> ✨ Add RSS feed for latest news #1988

web/pages/_app.tsx, web/pages/_document.tsx
=> 🐛 Move GTM setup to _app #1924

web/securityHeaders.js
Reverts equinor/energyvision#2059
=> Revert "♻️ Extract urls and make cookiebot url a wildcard #2058"

web/pnpm-lock.yaml
=> ⬆️ Fix pnpm-lock file #2069

web/lib/algolia.ts, web/package.json, web/pageComponents/pageTemplates/newsroom/UncontrolledSearchBox.tsx, web/pageComponents/search/Search.tsx, web/pageComponents/search/SearchBox.tsx, web/pnpm-lock.yaml
=> ✨ Add caching strategy and double debounce time #1987

web/lib/config.ts
=> ✨ Upgrade api version of sanity in web #2107

web/pageComponents/pageTemplates/shared/SharedPageContent.tsx, web/pageComponents/topicPages/promotions/MultiplePromotions.tsx
Added a fix for current code, and one proposed refactor with fix
=> applyPaddingTopIfApplicable does not take themes into consideration #2302

web/sections/Grid/GridTeaser.tsx
Reduces horizontal padding on grid teaser elements for improved layout consistency.
=> 💄 Adjusts grid teaser padding #3078
